<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use function foo\func;

class Order extends Model
{
    const PENDING = 'pending';
    const PROCESSING = 'processing';
    const PAYMENT_FAILED = 'payment_failed';
    const COMPLETED = 'completed';

	public function productVariations()
	{
		return $this->belongsToMany(ProductVariation::class);
	}

	public function user()
	{
		return $this->belongsTo(User::class);
	}

	public function address()
	{
		return $this->belongsTo(Address::class);
	}

	public function shippingMethod()
	{
		return $this->belongsTo(ShippingMethod::class);
	}

	public static function boot()
	{
		parent::boot(); // TODO: Change the autogenerated stub

		static::creating(function ($order) {
			$order->status = self::PENDING;
		});
	}
}
